name: darrell.odonnell
favicon: null
layout_spectrum: 0.47484813653863966
typography_spectrum: 0.9695295738056302
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1919'
    - '#ffffff'
    - '#b3303d'
    - '#a09e9b'
    - '#4a4848'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
